name: Lint

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
        
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
         
      - run: yarn install
        
      - name: Run ESLint
        run: yarn lint
        env:
          CI: true
